### ISSUE TITLE
Paragrafreferanse gir ikke mening

### ISSUE THREAD

**Issue by titaenstad** [ifilist/vedtekter#2]
I §7.4 står det:

> Internmedlemskapet varer frem til neste generalforsamling, så lenge den interne stadig oppfyller kravene i §3.1 og §3.3

men  §3.1 og §3.3 omhandler generalforsamling, og har ikke noe med interne å gjøre. Disse skal sannsynligvis være  §7.1 og §7.3.

**Comment by einarhb** [comment]
Endret på genfors h21, se #3
